config/routes.rb
ColumbiaRepairReportPlatform::Application.routes.draw do
  resources :reports
  # map '/' to be a redirect to '/reports'
  root :to => 'pages#home'

  get 'report/:id/complete', to: 'reports#complete', as: :complete_report
  post 'report/:id/comment', to:'reports#addcmt', as: :addcmt_report

  # routes for qrcode
  get 'qrcode', to: 'pages#qrcode_generate', as: 'qrcode'
  get 'qrcode_download', to: 'pages#qrcode_download', as: 'qrcode_download'

  # manager routes
  resources :managers, only: [:new, :create, :edit, :update, :show, :destroy]

  # session routes
  get '/login', to: 'sessions#login', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  post '/logout', to: 'sessions#destroy'
end

app/models/report.rb
class Report < ActiveRecord::Base
    has_many :comments
    mount_uploader :file, FileUploader
    def self.problemlist
        return [
            "Miscellaneous/Other",
            "Air Conditioning/Heating",
            "Bathroom/Restroom Items",
            "Ceiling",
            "Classroom Equipment",
            "Clean + Go Green",
            "Cleaning",
            "Computer & Projector",
            "Detectors/Alarms", 
            "Door",
            "Elevator",
            "Floor",
            "Furnishings - Classroom",
            "Furnishings - Other",
            "Hand Sanitizer",
            "Internet/WIFI",
            "Lab Fixtures/Services",
            "Lights",
            "Locks & Keys",
            "Moving/Carting",
            "Paint",
            "Pest Control",
            "Plumbing Services",
            "Power",
            "Recycling",
            "Stairs - Eexterior",
            "Stairs - Interior",
            "Switches/Sockets",
            "Walkway - Exterior",
            "Wall",
            "Windows/Glass",
        ]
    end

    def self.check_and_create(report_params)
        if Report.where(building: report_params[:building], area: report_params[:area]).take.nil?
            report_params[:status] = "Uncompleted"
            report = Report.create!(report_params)
            if report_params[:emergencylevel] == 'Urgent'
                Manager.all.each do |manager|
                  NoticeMailer.urgent_notice(manager.email, report).deliver_later
                end
                return "successfully published and managers are notified"
            end
            return "successfully published"
        else
            return "Already been published"
        end
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show]

  def show
    id = params[:id] # retrieve report ID from URI route
    @report = Report.find(id) # look up report by unique ID
    # will render app/views/reports/show.<extension> by default
  end

  def index
    @completed_checked = params[:show_complete]
    @emer_only_checked = params[:emer_only]
    if params[:problem_type].nil?
      params[:problem_type] = Hash.new
      params[:problem_type][:problem_type] = "All"
    end
    @selected = params[:problem_type][:problem_type]
      

    @problemlist = Report.problemlist.prepend("All")

    @reports = Report.where(status: "Uncompleted")

    if !params[:show_complete].nil?
      @reports = Report
    end

    if !params[:emer_only].nil?
      @reports = @reports.where(emergencylevel: "Urgent")
    end

    if @reports == Report
      @reports = Report.all
    end

    if !params[:problem_type].nil? && params[:problem_type][:problem_type] != "All"
      @reports = @reports.where(problemtype: params[:problem_type][:problem_type])
    end

    session[:emer_only]=params[:emer_only]
    session[:show_complete] = params[:show_complete]
  end

  def new
    @problemlist = Report.problemlist
    @prefilled_building = ''
    @prefilled_area = ''
    if params[:report] != nil
      building = params[:report][:building]
      area = params[:report][:area]
      @prefilled_building = building if building != nil
      @prefilled_area = area if area != nil
    end
  end

  def create
    if ReportsHelper.valid_uni?(report_params[:uni])
      flash[:notice] = Report.check_and_create(report_params)
    else
      flash[:notice] = "invalid UNI"
    end

    redirect_to root_path
  end

  def edit
    @report = Report.find params[:id]
  end

  def complete
    report = Report.find params[:id]
    flash[:notice] = "Marked as complete successful"
    report.status = "Completed"
    if report.save
      NoticeMailer.send_notice(report.uni, report).deliver_later
      redirect_to report_path(report)
    end
  end

  def addcmt
    report = Report.find params[:id]
    if params[:comment][:cmt].blank?
      flash[:notice] = "Cannot add a blank comment"
    else 
      flash[:notice] = "Comment successfully added"
      report.comments.build(:comment => params[:comment][:cmt], :manager_id=>session[:manager_id])
      report.save
    end 
    redirect_to report_path(report)
  end

  def update
    @report = Report.find params[:id]
    @report.update_attributes!(report_params)
    flash[:notice] = "#{@report.id} was successfully updated."
    redirect_to report_path(@report)
  end

  def destroy
    # @report = Report.find(params[:id])
    # @report.destroy
    # flash[:notice] = "Report '#{@report.id}' completed."
    # redirect_to reports_path
  end

  private
  # Making "internal" methods private is not required, but is a common practice.
  # This helps make clear which methods respond to requests, and which ones do not.
  def report_params
    params.require(:report).permit(:building, :area, :problemtype, :emergencylevel, :uni, :description, :file)
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
  def self.valid_uni?(uni)
    uni.match?(/^[a-z][a-z][0-9][0-9][0-9][0-9]$/x) or uni.match?(/^[a-z][a-z][a-z][0-9][0-9][0-9][0-9]$/x)
  end
end

app/views/reports/edit.html.erb
<h2 class="text-columbia">Manage Current Report</h2>

<%= form_tag report_path(@report), :method => :put, :multipart => true, :id => 'form' do %>
  <%= label :report, :building, 'Location: Building', :class => 'col-form-label' %>
  <%= text_field :report, :building, :class => 'form-control' %>
  <%= label :report, :area, 'Location: Area', :class => 'col-form-label' %>
  <%= text_field :report, :area, :class => 'form-control' %>
  <%= label :report, :problemtype, 'Problem Type', :class => 'col-form-label'%>
  <%= select :report, :problemtype, ['Carpentry', 'Electronic','Floor','Furniture','Laundry','Mechanical','Pest Control','Housekeeping','Heating/Air Conditioning', 'Plumbing', 'Other'], {}, {:class => 'form-control col-3'} %>
  <%= label :report, :emergencylevel, 'Emergency Level', :class => 'col-form-label'  %>
  <%= select :report, :emergencylevel, ['Emergent','Ordinary'], {}, {:class => 'form-control col-3'} %>
  <%= label :report, :description, 'Description', :class => 'col-form-label' %>
  <%= text_area :report, :description, :class => 'form-control' %>
  <%= label :report, :file, 'Image', :class => 'col-form-label' %>
  <%= file_field :report, :file, :class => 'form-control' %>
  <br/>
  <%= submit_tag 'Update Report Info', :class => 'btn btn-columbia' %>
  <%= link_to 'Cancel', report_path(@report), :class => 'btn btn-secondary' %>
<% end %>

app/views/reports/index.html.erb
<!--  This file is app/views/reports/index.html.erb -->


<h2 class="text-columbia"> Reports</h2>

<br>

<a class="btn text-columbia" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
  <img src="/assets/filters.png" style="width:20px;height:20px;"/>
  Filters
</a>
<div class="collapse" id="collapseExample">
  <%= form_tag reports_path, method: :get, id: 'filter_form' do %>
    <div class="form-check  form-check-inline">
      <%= label_tag "emer_only", "Show Urgent Reports Only", class: 'form-check-label' %>
      <%= check_box_tag "emer_only", "1",  @emer_only_checked, class: 'form-check-input' %>
    </div>
    <div class="form-check  form-check-inline">
      <%= label_tag "show_complete", "Show Completed Reports", class: 'form-check-label' %>
      <%= check_box_tag "show_complete", "1",  @completed_checked, class: 'form-check-input' %>
    </div>
    <div class="form-row">
      <%= label "problem_type", "problem_type", 'Problem Type', :class => 'col-form-label'%>
      <div class="col-sm-3">
        <%= select "problem_type", "problem_type", @problemlist, {:selected=>@selected}, :class => 'form-control' %>
      </div>
    </div>
    <%= submit_tag 'Save', id: 'filter_submit', class: 'btn btn-columbia' %>
  <% end %>
</div>

<br>

<table class="table table-striped col-md-12" id="reports">
  <thead>
    <tr>
      <th>Building</th>
      <th>Area</th>
      <th>ProblemType</th>
      <th>Emergency Level</th>
      <th>Status</th>
      <th>More Info</th>
    </tr>
  </thead>
  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td>
          <%= report.building %>
        </td>
        <td>
          <%= report.area %>
        </td>
        <td>
          <%= report.problemtype %>
        </td>
        <td>
          <%= report.emergencylevel %>
        </td>
        <td>
          <%= report.status %>
        </td>
        <td>
          <%= link_to "More about", report_path(report)%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<!-- <%= link_to 'Start New Report', new_report_path, :class => 'btn btn-success' %> -->
<%= link_to 'Generate QR Code', qrcode_path, :class => 'btn btn-columbia col-2' %>

app/views/reports/new.html.erb
<h2 class="text-columbia">Create New Report</h2>

<%= form_tag reports_path, :class => 'form', :multipart => true, :id => 'form' do %>
  <%= label :report, :building, 'Location: Building', :class => 'col-form-label' %>
  <%= text_field :report, :building, :value => @prefilled_building, :class => 'form-control' %>
  <%= label :report, :area, 'Location: Area', :class => 'col-form-label' %>
  <%= text_field :report, :area, :value => @prefilled_area, :class => 'form-control' %>
  <%= label :report, :uni, 'Please enter your UNI', :class => 'col-form-label' %>
  <%= text_field :report, :uni, :class => 'form-control' %>
  <%= label :report, :description, 'Description', :class => 'col-form-label' %>
  <%= text_area :report, :description, :class => 'form-control' %>
  <%= label :report, :file, 'Image', :class => 'col-form-label' %>
  <%= file_field :report, :file, :class => 'form-control' %>
  <%= label :report, :problemtype, 'Problem Type', :class => 'col-form-label'%>
  <%= select :report, :problemtype, @problemlist, {}, :class => 'form-control col-3' %>
  <%= label :report, :emergencylevel, 'Emergency Level', :class => 'col-form-label'  %>
  <%= select :report, :emergencylevel, ['Ordinary','Urgent'], {}, :class => 'form-control col-3' %>
  <br/>
  <%= submit_tag 'Publish', :class => 'btn btn-columbia' %>
  <%= link_to 'Cancel', root_path, :class => 'btn btn-secondary' %>
<% end %>

app/views/reports/show.html.erb
<!--  app/views/reports/show.html.erb -->
<h2 class="text-columbia">Specific Details of Issue </h2>

<ul id="details">
  <h2 style="font-size: 22px;">Location: </h2>

  <li style="margin-left: 14px;">
    Building:
    <%= @report.building %>
  </li>
  <li style="margin-left: 14px;">
    Area:
    <%= @report.area %>
  </li>
  <br>
  <h2 style="font-size: 22px;">Problem Information: </h2>
  <li style="margin-left: 14px;">
    Problem Type:
    <%= @report.problemtype %>
  </li>
  <li style="margin-left: 14px;">
    Emergency Level:
    <%= @report.emergencylevel %>
  </li>
  <li style="margin-left: 14px;">
    Description:
    <% if @report.description.blank? %>
    No Description
    <%else %>
    <%= @report.description %>
    <%end%>
  </li>
  <li style="margin-left: 14px;">
    Image:
    <% if @report.file_url.nil? %>
    No Image
    <%else %>
    <%= image_tag @report.file_url, size: '100x100' %>
    <%end%>
  </li>
  <li style="margin-left: 14px;">
    Complete Status:
    <%= @report.status %>
  </li>
  <br>
  <h2 style="font-size: 22px;">Comments: </h2>
  <%@report.comments.all.each do |cmt|%>
    <li style="margin-left: 14px;"> 
      <%= cmt.manager.name%>: <%= cmt.comment%>
    </li>
  <% end %>
  <li style="margin-left: 14px;"> 
    <%= form_tag addcmt_report_path(@report) do %>
      <div class="form-row">
        <%= text_field :comment, :cmt, :class => 'form-control col-sm-5' %>
        <%= submit_tag 'Add Comment', :class => 'btn btn-columbia' %>
      </div>
    <% end %>
  </li>
</ul>

<br>

<div class="row">
  <%= link_to 'Management', edit_report_path(@report), :class => 'btn btn-columbia col-2' %>
  <% if @report.status == "Uncompleted"%>
    <%= link_to 'Mark as Completed', complete_report_path(@report), 'data-confirm' => 'Are you sure?', :class => 'btn btn-danger col-2' %>
  <% else %>
    <div class="btn btn-primary col-2"> Already compeleted </div>
  <% end %>
  <%= link_to 'Back to Report List', reports_path, :class => 'btn btn-columbia col-2' %>
</div>